const asset = (path) => `${import.meta.env.BASE_URL}assets/${path}`;

export const journeyConfig = {
  recipientName: "",
  senderName: "",
  openingText: "有些风景，想先替你收藏。",
  finalWish: "愿你走遍世界，也永远有人陪你看风景。",
  audioSrc: "",
  stops: [
    {
      id: "kyoto",
      city: "京都",
      country: "Japan",
      coordinates: "35.01° N · 135.77° E",
      lat: 35.0116,
      lon: 135.7681,
      image: asset("kyoto.jpg"),
      title: "等一场安静的\n樱花雨",
      wish: "愿匆忙的世界里，始终有值得你慢下来欣赏的风景。",
      color: "#f4b8cf",
      credit: "Zhaoli JIN / Unsplash",
      source: "https://unsplash.com/photos/kpAPi3UoZbY",
    },
    {
      id: "switzerland",
      city: "瑞士",
      country: "Switzerland",
      coordinates: "46.82° N · 8.23° E",
      lat: 46.8182,
      lon: 8.2275,
      image: asset("switzerland.jpg"),
      title: "坐上列车\n穿过群山",
      wish: "愿每一段路，都把你带向更辽阔、更自由的地方。",
      color: "#9de2dc",
      credit: "Seungji Ryu / Unsplash",
      source: "https://unsplash.com/photos/ofg1SUwYcZA",
    },
    {
      id: "iceland",
      city: "冰岛",
      country: "Iceland",
      coordinates: "64.96° N · 19.02° W",
      lat: 64.9631,
      lon: -19.0208,
      image: asset("iceland.jpg"),
      title: "去看极光\n落进雪原",
      wish: "愿你一直保有出发的勇气，也总能遇见意料之外的光。",
      color: "#7ef2bd",
      credit: "Jonatan Pie / Unsplash",
      source: "https://unsplash.com/photos/iokiwAq05UU",
    },
    {
      id: "santorini",
      city: "圣托里尼",
      country: "Greece",
      coordinates: "36.39° N · 25.46° E",
      lat: 36.3932,
      lon: 25.4615,
      image: asset("santorini.jpg"),
      title: "在爱琴海边\n等一次日落",
      wish: "愿温柔的晚风，把生活里所有疲惫都轻轻吹散。",
      color: "#ffd39a",
      credit: "Tânia Mousinho / Unsplash",
      source: "https://unsplash.com/photos/DvDnHdWSo-k",
    },
    {
      id: "patagonia",
      city: "巴塔哥尼亚",
      country: "Argentina",
      coordinates: "49.30° S · 73.00° W",
      lat: -49.3,
      lon: -73,
      image: asset("patagonia.jpg"),
      title: "走到世界\n更远的地方",
      wish: "愿远方永远值得期待，也愿每一次归来都有人惦念。",
      color: "#b7c8ff",
      credit: "Marek Piwnicki / Unsplash",
      source: "https://unsplash.com/photos/_mgP1tYBpcw",
    },
  ],
};
